### ISSUE TITLE
Grid3 выдает 2 кнопки в сетке вместо трех на десктопе

### ISSUE THREAD

**Issue by dyakovri** [profcomff/navbar-element#11]

**Comment by dyakovri** [comment]
![Image](https://user-images.githubusercontent.com/5656720/188171233-7853f09e-fd37-49c2-a85d-699c9502c413.png)

**Comment by annndruha** [comment]
Кажется, починить это можно убрав из css класса `services` атрибут `gap: 1vmin;`

**Comment by ilya101master** [comment]
Проблема возникает при изменении размеров окна после загрузки страницы, чинится фиксированными размерами области с кнопками. Нужно обсудить ожидаемое поведение

**Comment by annndruha** [comment]
Если там обычный css то мне кажется окно не зачем фиксировать. В css есть размеры относительно экрана, можно поставить минимальные и максимальные значения.
