### ISSUE TITLE
Некорректное поведение кнопки "назад"

### ISSUE THREAD

**Issue by dyakovri** [profcomff/navbar-element#12]
**Expected**
Вернуться на предыдущую страницу, вернуться на предыдущую страницу, выйти

**Actual**
- При нажатии "назад" на меню приложений расписание появляется под меню
- При нажатии "назад" после перехода с меню приложений на расписание

**Suggestion**
Скорее всего дело в том, что навбар не обновляет состояние перехода (обычно он делает это при нажатиях на кнопку) и не скрывает/раскрывает меню

**Suggested Solution**
- Выделить меню приложений в отдельный микросервис
- Не поможет с верхним меню, но верхнее меню надо научить жрать кнопки из событий монтирования микроаппов, а не просто выключать на календаре

**Comment by ilya101master** [comment]
Проблема в роутинге от навбара, кажется нужно его просто переписать по-человечески через router.push, но нужно пояснение к текущей работе

**Comment by dyakovri** [comment]
В логах дофига ворнингов, надо фиксить

**Comment by dyakovri** [comment]
Не работает переход между сервисами из страницы timetable/init
