### ISSUE TITLE
Кот в сервисах подгружается раньше чем тело страницы.

### ISSUE THREAD

**Issue by dyakovri** [profcomff/navbar-element#14]
При переходе из расписания в сервисы сразу подгружается кот, а лишь после сама страница. Выглядит как недочёт.
Нужно либо пофиксить порядок загрузки, либо сделать статус-круг как во вкладке расписание.

https://user-images.githubusercontent.com/51162917/188281141-f46a6f5c-1a00-44e7-8c99-a7c48af40e57.mp4

**Comment by ilya101master** [comment]
Добавлен loader на время маунта
